[tool.black]
line-length = 120

[tool.ruff]
line-length = 120

target-version = "py39"

select = [
    "E",  # pycodestyle
    "W",  # pycodestyle
    "F",  # pyflakes
    "I",  # isort
]
ignore = []
exclude = [
    "migrations/versions/",
    "venv*",
    "__pycache__",
    "node_modules",
    "cache",
    "migrations",
    "build",
    "sample_cap_xml_documents.py",
]
